
SELECT TOP 100 LTRIM(SZLASZAM) AS SZLASZAM, BIZSORSZ AS SORSZAM, CONVERT(date, BIZDAT) AS DATUM, LTRIM(PARTNER) AS PARTNER, OSSZEG, DEVIZA, DEVOSSZEG
	FROM PKARTON2021
	WHERE PARTNER IS NOT NULL AND OSSZEG > 0 AND DEVOSSZEG > 0
	ORDER BY SZLASZAM, BIZSORSZ

--SELECT LTRIM(PARTNER) AS PARTNER, NEV FROM PARTNER
